### ISSUE TITLE
cuda compile issue 

### ISSUE THREAD

**Issue by renyangry** [arcadelab/deepdrr#130]
Hi, 

I have followed the installation instruction and was trying out the example_projector.py. 
However, I am getting this error message and have no idea how to slove it. 
Traceback (most recent call last):
  File "/home/rgu/Documents/GitHub/S3_knee_segmentation/ct2x_angled.py", line 56, in <module>
    main()
  File "/home/rgu/Documents/GitHub/S3_knee_segmentation/ct2x_angled.py", line 46, in main
    with Projector(patient, carm=carm) as projector:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgu/miniconda3/lib/python3.11/site-packages/deepdrr/projector/projector.py", line 306, in __init__
    self.mod = _get_kernel_projector_module(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgu/miniconda3/lib/python3.11/site-packages/deepdrr/projector/projector.py", line 138, in _get_kernel_projector_module
    return SourceModule(
           ^^^^^^^^^^^^^
  File "/home/rgu/miniconda3/lib/python3.11/site-packages/pycuda/compiler.py", line 355, in __init__
    cubin = compile(
            ^^^^^^^^
  File "/home/rgu/miniconda3/lib/python3.11/site-packages/pycuda/compiler.py", line 304, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgu/miniconda3/lib/python3.11/site-packages/pycuda/compiler.py", line 90, in compile_plain
    checksum.update(preprocess_source(source, options, nvcc).encode("utf-8"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgu/miniconda3/lib/python3.11/site-packages/pycuda/compiler.py", line 58, in preprocess_source
    raise CompileError(
pycuda.driver.CompileError: nvcc preprocessing of /tmp/tmpozfdc8zt.cu failed
[command: nvcc --preprocess -D NUM_VOLUMES=1 -D NUM_MATERIALS=3 -D ATTENUATE_OUTSIDE_VOLUME=0 -D AIR_INDEX=0 -arch sm_89 -I/home/rgu/miniconda3/lib/python3.11/site-packages/deepdrr/projector/cubic -I/home/rgu/miniconda3/lib/python3.11/site-packages/deepdrr/projector -I/home/rgu/miniconda3/lib/python3.11/site-packages/pycuda/cuda /tmp/tmpozfdc8zt.cu --compiler-options -P]
[stderr:
b"nvcc fatal   : Value 'sm_89' is not defined for option 'gpu-architecture'\n"]

I am currently on cuda v10.1.  Appreciation on any suggestion for it.

**Comment by yanlend** [comment]
Your GPU is too new for the CUDA version you are using, see: https://de.wikipedia.org/wiki/CUDA

Cuda compute capability 8.9 (sm_89) is only supported beginning with Cuda toolkit version 11.8.
